version: "3.1"
services:
  mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - ~/mongo/data:/data/db

  api:
    build:
      context: ./packages/api
    volumes:
      - "./packages/api:/opt/api"
    ports:
      - "3000:3000"
